export const quotes = [
  "The only way to do great work is to love what you do. — Steve Jobs",
  "Success is not final, failure is not fatal: it is the courage to continue that counts. — Winston Churchill",
  "Believe you can and you're halfway there. — Theodore Roosevelt",
  "Your time is limited, so don't waste it living someone else's life. — Steve Jobs",
  "Hardships often prepare ordinary people for an extraordinary destiny. — C.S. Lewis",
  "The future belongs to those who believe in the beauty of their dreams. — Eleanor Roosevelt",
  "The best way to predict the future is to create it. — Peter Drucker",
  "Everything you've ever wanted is on the other side of fear. — George Addair",
  "Success usually comes to those who are too busy to be looking for it. — Henry David Thoreau",
  "Don't be afraid to give up the good to go for the great. — John D. Rockefeller",
  "I find that the harder I work, the more luck I seem to have. — Thomas Jefferson",
  "Success is walking from failure to failure with no loss of enthusiasm. — Winston Churchill",
  "The only limit to our realization of tomorrow will be our doubts of today. — Franklin D. Roosevelt",
  "Do one thing every day that scares you. — Eleanor Roosevelt",
  "Dream big and dare to fail. — Norman Vaughan",
  "What you get by achieving your goals is not as important as what you become by achieving your goals. — Zig Ziglar",
  "Action is the foundational key to all success. — Pablo Picasso",
  "If you want to achieve greatness stop asking for permission. — Anonymous",
  "Things work out best for those who make the best of how things work out. — John Wooden",
  "To live a creative life, we must lose our fear of being wrong. — Anonymous",
  "Trust because you are willing to accept the risk, not because it's safe or certain. — Anonymous",
  "All our dreams can come true if we have the courage to pursue them. — Walt Disney",
  "Good things come to people who wait, but better things come to those who go out and get them. — Anonymous",
  "If you do what you always did, you will get what you always got. — Anonymous",
  "Success is the sum of small efforts, repeated day-in and day-out. — Robert Collier",
  "Whether you think you can or you think you can't, you're right. — Henry Ford",
  "I have not failed. I've just found 10,000 ways that won't work. — Thomas Edison",
  "A person who never made a mistake never tried anything new. — Albert Einstein",
  "The only person you are destined to become is the person you decide to be. — Ralph Waldo Emerson",
  "Go confidently in the direction of your dreams. Live the life you have imagined. — Henry David Thoreau",
  "Don't judge each day by the harvest you reap but by the seeds that you plant. — Robert Louis Stevenson",
  "The secret of getting ahead is getting started. — Mark Twain",
  "You miss 100% of the shots you don't take. — Wayne Gretzky",
  "I've failed over and over and over again in my life and that is why I succeed. — Michael Jordan",
  "The mind is everything. What you think you become. — Buddha",
  "The best time to plant a tree was 20 years ago. The second best time is now. — Chinese Proverb",
  "An unexamined life is not worth living. — Socrates",
  "Eighty percent of success is showing up. — Woody Allen",
  "Your time is limited, so don't waste it living someone else's life. — Steve Jobs",
  "Winning isn't everything, but wanting to win is. — Vince Lombardi",
  "I am not a product of my circumstances. I am a product of my decisions. — Stephen Covey",
  "Every child is an artist. The problem is how to remain an artist once he grows up. — Pablo Picasso",
  "You can never cross the ocean until you have the courage to lose sight of the shore. — Christopher Columbus",
  "Either you run the day, or the day runs you. — Jim Rohn",
  "Whether you think you can or you think you can't, you're right. — Henry Ford",
  "The two most important days in your life are the day you are born and the day you find out why. — Mark Twain",
  "Whatever you can do, or dream you can, begin it. Boldness has genius, power and magic in it. — Johann Wolfgang von Goethe",
  "The best revenge is massive success. — Frank Sinatra",
  "People often say that motivation doesn't last. Well, neither does bathing. That's why we recommend it daily. — Zig Ziglar",
  "Life shrinks or expands in proportion to one's courage. — Anais Nin",
  "If you hear a voice within you say 'you cannot paint,' then by all means paint and that voice will be silenced. — Vincent Van Gogh",
  "There is only one way to avoid criticism: do nothing, say nothing, and be nothing. — Aristotle",
  "Ask and it will be given to you; seek and you will find; knock and the door will be opened to you. — Jesus",
  "The only person you are destined to become is the person you decide to be. — Ralph Waldo Emerson"
];
